nodeLinker: node-modules

npmScopes:
  numeric-io:
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_TOKEN}'
    npmRegistryServer: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-3.6.4.cjs
